tinyMCE.init({

   theme : "advanced",
   skin: "wp_theme",
   mode: "exact",
   elements : "optinrev_excerpt_content",
   object_resizing : false,
   cleanup : false,
   plugins : "textedit,inlinepopups,layer,textbox,input_align,ifdragedit,object_align,text_align",
   apply_source_formatting : false,
   theme_advanced_buttons1 : "textedit,|,moveforward,movebackward,|,textbox,|,text_align_left,text_align_center,text_align_justify,text_align_right,|,input_align_left,input_align_top,|,object_align_top,object_align_bottom,object_align_center,object_align_left,object_align_right,|,undo,redo,ifdragedit,ifdragedithelp",
   theme_advanced_buttons2 : '',
   theme_advanced_buttons3 : '',
   theme_advanced_buttons4 : '',
   theme_advanced_toolbar_location : "top",
   theme_advanced_toolbar_align : "left",
   theme_advanced_resizing : true,
   invalid_elements  : 'p',
   force_br_newlines : true,
   force_p_newlines : false,
   forced_root_block : '',
   document_base_url: doc_base_url,
   setup : 'wtfn.tinymce',
   handle_event_callback : 'wtfn.tinymce_event',
   content_css : wtp + 'optinrev-css.php'
});